version: "3"
services:
  test_db:
    image: test_db
    container_name: test_db
    build:
      context: ./dockerfile/mysqltest
      dockerfile: ./Dockerfile.local
    volumes:
      - ./dockerfile/mysqltest/db:/docker-entrypoint-initdb.d #初期データ
    environment:
      MYSQL_ROOT_PASSWORD: Qu849dzp
      MYSQL_DATABASE: test_db
      TZ: "UTC"
    ports:
      - "127.0.0.1:3306:3306"
  go-test-server:
    image: go-test-server
    container_name: go-test-server
    build:
      context: ./goapi
      dockerfile: ../dockerfile/gotest/Dockerfile.local
    environment:
      # MYSQL_USER: "root"
      # MYSQL_PASSWORD: "Qu849dzp"
      MYSQL_PROTOCOL: "test_db:3306"
      MYSQL_DATABASE: "test_db"
      SECRET_KEY: "9tpvjAWvuqma"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    #   MYSQL_PROTOCOL: ${MYSQL_PROTOCOL}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   SECRET_KEY: ${SECRET_KEY}
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - test_db
