version: '3'
services:
  nextapp:
    image: nextapp
    container_name: nextapp
    build:
      context: ./nextapp
      dockerfile: ../dockerfile/nextapp/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    tty: true
    volumes:
     - .:/nextapp #ホスト:コンテナ
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
  db:
    image: cafekatu_db
    container_name: cafekatu_db
    build: 
        context: ./dockerfile/mysql
        dockerfile: ./Dockerfile
    #volumes:
    #  - ./db:/docker-entrypoint-initdb.d  #初期データ
    environment:
      MYSQL_ROOT_PASSWORD: cafe-password
      TZ: "UTC"
    ports:
      - "127.0.0.1:3307:3306"
  api-server:
    image: go-api-server
    container_name: go-api-server
    build:
      context: ./goapi
      dockerfile: ../dockerfile/goapi/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
     - db
  