FROM golang:1.18-alpine3.15 as builder

RUN apk add build-base

ARG ROOT=/go/src/github.com/akane-05/cafekatu/goapi
WORKDIR ${ROOT}

COPY go.mod go.sum main.go ./
COPY main_test.go ./
COPY controller/ ./controller/
COPY model/ ./model/
COPY unit/ ./unit/
RUN go mod download

EXPOSE 8081

CMD ["go", "run", "main.go"]
